sudo: required
services:
  - docker

before_install:
  - docker build -t aalexis8/react-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true aalexis8/react-docker yarn test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'react-docker'
  env: 'Reactdocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-017075549921'
  bucket_path: 'react-docker'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
